version: "3"

services:
  openwayback:
    volumes:
      - ${INPUT_DIR}:/data
      - ${WARC_DIR}:/data/files1
    environment:
      - WAYBACK_URL_HOST=${WAYBACK_URL_HOST}
      - WAYBACK_URL_PREFIX=${WAYBACK_URL_PREFIX}
